-- Find Total Customers by Countries
   SELECT
   country,
   COUNT(customer_key) Total_customers
   FROM dbo.dim_customers
   GROUP BY country
   ORDER BY Total_customers DESC

-- Find Total Customers by Gender
   SELECT 
   gender,
   COUNT(customer_key) Total_customers
   FROM dbo.dim_customers
   GROUP BY gender 
   ORDER BY Total_customers DESC

-- Find Total Products by category
   SELECT 
   category,
   COUNT(product_key) Total_products
   FROM dbo.dim_products
   GROUP BY category 
   ORDER BY Total_products DESC

-- What is Average costs in each categories?
   SELECT 
   category,
   AVG(cost) Avg_costs
   FROM dbo.dim_products
   GROUP BY category 
   ORDER BY Avg_costs DESC

-- What is the total revenue generated for each categories?
   SELECT 
   p.category,
   SUM(f.sales_amount) AS total_revenue
   FROM dbo.fact_sales f
   LEFT JOIN dbo.dim_products p
   ON p.product_key = f.product_key
   GROUP BY p.category
   ORDER BY total_revenue DESC

-- Find total revenue is generated by each customers
   SELECT 
   c.customer_key,
   c.first_name,
   c.last_name,
   SUM(f.sales_amount) AS total_revenue
   FROM dbo.fact_sales f
   LEFT JOIN dbo.dim_customers c
   ON c.customer_key = f.customer_key
   GROUP BY 
   c.customer_key,
   c.first_name,
   c.last_name
   ORDER BY total_revenue DESC

-- What is the distribution of sold items across countries?
   SELECT 
   c.country,
   SUM(f.quantity) AS total_sold_items
   FROM dbo.fact_sales f
   LEFT JOIN dbo.dim_customers c
   ON c.customer_key = f.customer_key
   GROUP BY
   c.country
   ORDER BY total_sold_items DESC
